# Generated by Django 5.0.7 on 2024-07-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Course', max_length=100)),
                ('description', models.TextField(default='No description available')),
                ('image', models.URLField(default='https://example.com/default-image.jpg')),
                ('type', models.CharField(default='General', max_length=50)),
                ('difficulty', models.CharField(default='Beginner', max_length=20)),
                ('duration', models.CharField(default='Duration not specified', max_length=50)),
                ('instructor', models.CharField(default='TBA', max_length=100)),
                ('syllabus', models.JSONField(default=list)),
                ('reviews', models.JSONField(default=list)),
                ('averageRating', models.FloatField(default=0.0)),
                ('progress', models.CharField(default='0%', max_length=10)),
            ],
        ),
    ]
