# Generated by Django 5.0.7 on 2024-07-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_remove_course_averagerating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
